services:

  backend:
    build:
      context: .
      dockerfile: ./servers/user-server/dockerfile
    container_name: user_server
    restart: always
    ports:
      - "7001:7001"
    # env_file:
    #   - ./servers/user-server/.env
