FROM node:22-alpine AS builder

WORKDIR /workspace

COPY packages ./packages

RUN npm install -g pnpm

WORKDIR /workspace/packages/database
RUN pnpm install && pnpm run build

WORKDIR /workspace/packages/logger
RUN pnpm install && pnpm run build


WORKDIR /workspace

COPY servers/user-server/package*.json ./servers/user-server/

WORKDIR /workspace/servers/user-server
RUN pnpm install

COPY servers/user-server/package*.json ./
COPY servers/user-server/tsconfig.json ./
COPY servers/user-server/src ./src

RUN pnpm run build

# ------------------------------------------------------------

# Production stage
FROM node:22-alpine

WORKDIR /workspace

# Copy built assets from builder
COPY --from=builder /workspace/packages ./packages
COPY --from=builder /workspace/servers/user-server/dist ./servers/user-server/dist
COPY --from=builder /workspace/servers/user-server/package*.json ./servers/user-server/

WORKDIR /workspace/servers/user-server

ENV NODE_ENV=production

RUN npm install -g pnpm

RUN pnpm i --prod

EXPOSE 7003

CMD ["node", "dist/index.js"]
